.PHONY: clean All

All:
	@echo "----------Building project:[ Practica1Ubuntu - Debug ]----------"
	@"$(MAKE)" -f  "Practica1Ubuntu.mk"
clean:
	@echo "----------Cleaning project:[ Practica1Ubuntu - Debug ]----------"
	@"$(MAKE)" -f  "Practica1Ubuntu.mk" clean
